

# Example configuration entry
output:
  - platform: ledc
    id: motor_reverse_pin
    pin: 25

  - platform: ledc
    id: motor_forward_pin
    pin: 26



fan:
  - platform: hbridge
    id: my_fan
    name: "DC Motor"
    pin_a: motor_forward_pin
    pin_b: motor_reverse_pin
    # enable_pin: motor_enable
    decay_mode: slow   # slow decay mode (braking) or fast decay (coasting)


binary_sensor:
  - platform: gpio
    pin: 33
    name: "Endstop 1"
    filters:
      - invert:

  - platform: gpio
    pin: 32
    name: "Endstop 2"
    filters:
      - invert: